services:

  - type: web
    name: agrinova-auth
    runtime: python
    plan: free
    branch: main
    repo: https://github.com/Fadelallagbe02/AgriNovaPlatform
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/auth_server.py
    healthCheckPath: /api/health

  - type: web
    name: agrinova-social
    runtime: python
    plan: free
    branch: main
    repo: https://github.com/Fadelallagbe02/AgriNovaPlatform
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/social_server.py
    healthCheckPath: /api/health

  - type: web
    name: agrinova-payment
    runtime: python
    plan: free
    branch: main
    repo: https://github.com/Fadelallagbe02/AgriNovaPlatform
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/payment_server.py
    healthCheckPath: /api/health
